all: myls mystat mysearch mytail

myls: myls-anzola.c
	gcc -o myls myls-anzola.c

mysearch: mysearch-anzola.c
	gcc -o mysearch mysearch-anzola.c

mystat: mystat-anzola.c
	gcc -o mystat mystat-anzola.c

mytail: mytail-anzola.c
	gcc -o mytail mytail-anzola.c
